.\" Pipe this output to groff -Tutf8 | less
.\"
.mso an.tmac
.TH "JSOO_MINIFY" 1 "" "Jsoo_minify 3.9.1" "Jsoo_minify Manual"
.\" Disable hyphenation and ragged-right
.nh
.ad l
.SH NAME
.P
jsoo_minify \N'45' JavaScript minifier
.SH SYNOPSIS
.P
\fBjsoo_minify\fR [\fIOPTION\fR]\N'46'\N'46'\N'46' [\fIJS_FILES\fR]\N'46'\N'46'\N'46'
.SH DESCRIPTION
.P
jsoo_minify is a JavaScript minifier\N'46'
.SH OPTIONS
.TP 4
\fB\N'45'\N'45'custom\N'45'header\fR=\fIVAL\fR
Provide a custom header for the generated JavaScript file, useful for making the script an executable file with #!/usr/bin/env node
.TP 4
\fB\N'45'\N'45'debug\fR=\fISECTION\fR
enable debug [\fISECTION\fR]\N'46'
.TP 4
\fB\N'45'\N'45'debuginfo\fR, \fB\N'45'\N'45'debug\N'45'info\fR
Output debug information\N'46'
.TP 4
\fB\N'45'\N'45'disable\fR=\fIOPT\fR
Disable optimization [\fIOPT\fR]\N'46'
.TP 4
\fB\N'45'\N'45'enable\fR=\fIOPT\fR
Enable optimization [\fIOPT\fR]\N'46'
.TP 4
\fB\N'45'\N'45'help\fR[=\fIFMT\fR] (default=auto)
Show this help in format \fIFMT\fR\N'46' The value \fIFMT\fR must be one of `auto\N'39', `pager\N'39', `groff\N'39' or `plain\N'39'\N'46' With `auto\N'39', the format is `pager` or `plain\N'39' whenever the \fBTERM\fR env var is `dumb\N'39' or undefined\N'46'
.TP 4
\fB\N'45'\N'45'noinline\fR, \fB\N'45'\N'45'no\N'45'inline\fR
Disable inlining\N'46'
.TP 4
\fB\N'45'o\fR \fIFILE\fR
Set output file name to [\fIFILE\fR]\N'46'
.TP 4
\fB\N'45'\N'45'pretty\fR
Pretty print the output\N'46'
.TP 4
\fB\N'45'q\fR, \fB\N'45'\N'45'quiet\fR
suppress non\N'45'error messages\N'46'
.TP 4
\fB\N'45'\N'45'stdin\fR
Read from standard input\N'46'
.TP 4
\fB\N'45'\N'45'version\fR
Show version information\N'46'
.SH BUGS
.P
Bugs are tracked on github at \fIhttps://github\N'46'com/ocsigen/js_of_ocaml/issues\fR\N'46'
.SH SEE ALSO
.P
js_of_ocaml(1)
.SH AUTHORS
.P
Jerome Vouillon, Hugo Heuzard\N'46'
.SH LICENSE
.P
Copyright (C) 2010\N'45'2019\N'46'
.P
jsoo_minify is free software, you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, with linking exception; either version 2\N'46'1 of the License, or (at your option) any later version\N'46'