# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - 'toplevel_build/**'
      - '!toplevel_build/BUILD.md'
    branches: [ master ]
  pull_request:
    paths:
      - 'toplevel_build/**'
      - '!toplevel_build/BUILD.md'
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install opam
        run : |
          sudo add-apt-repository ppa:avsm/ppa
          sudo apt update
          sudo apt install opam
          opam init
      
      - name: Compile
        run: |
          cd toplevel_build
          chmod +x compile.sh
          bash compile.sh 4.12.0
        
      - name: Check if file exist
        run: test -f "./toplevel_build/builds/topevel-4.12.0.js" || exit 1
      
      
      
